version: '3.8'
services:
  api:
    image: diabetes-api        # o puedes usar build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app                # monta todo tu proyecto
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
